name: Build Nativefier App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Nativefier globally
        run: npm install -g nativefier

      - name: Build Nativefier app
        run: nativefier --name "RPClogoDVD" --icon "./RPClogo.ico" --platform win32 --arch x64 --quiet "https://dvd.rpcgroup.xyz"

      - name: List current directory (for debugging)
        run: ls -l

      - name: List build output directory (for debugging)
        run: ls -l RPClogoDVD-win32-x64/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: RPClogoDVD-win32-x64
          path: RPClogoDVD-win32-x64/
