name: Build RPClogo DVD App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Nativefier
        run: npm install -g nativefier

      - name: Build Windows App with debug logs
        run: |
          nativefier "https://dvd.rpcgroup.xyz" \
            --name "RPClogo DVD" \
            --fullscreen \
            --disable-dev-tools \
            --verbose
          echo "Listing current directory contents:"
          ls -la
          echo "Listing contents of nativefier build folder:"
          ls -la "RPClogo DVD-win32-x64" || echo "Build folder not found"
          
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: RPClogo-DVD-Windows
          path: "RPClogo DVD-win32-x64/"
