name: Build Nativefier App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Nativefier globally
        run: npm install -g nativefier

      - name: List workspace before build
        run: ls -la

      - name: Build Nativefier app (verbose)
        run: nativefier --name "RPClogoDVD" --icon "./RPClogo.ico" --platform win32 --arch x64 --verbose "https://dvd.rpcgroup.xyz"

      - name: List workspace after build
        run: ls -la

      - name: Find build output directory
        id: finddir
        run: |
          folder=$(ls -d *-win32-x64 2>/dev/null || echo "")
          echo "folder=$folder"
          echo "::set-output name=folder::$folder"

      - name: List build output directory contents
        if: steps.finddir.outputs.folder != ''
        run: ls -la "${{ steps.finddir.outputs.folder }}"

      - name: Upload build artifact
        if: steps.finddir.outputs.folder != ''
        uses: actions/upload-artifact@v4
        with:
          name: RPClogoDVD-win32-x64
          path: ${{ steps.finddir.outputs.folder }}
