name: Build Nativefier Windows App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Nativefier globally
        run: npm install -g nativefier

      - name: Build Windows Nativefier app
        run: |
          nativefier "https://dvd.rpcgroup.xyz" --name "RPClogo DVD" --fullscreen --disable-dev-tools --platform win32

      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nativefier-windows-app
          path: ./RPClogo\ DVD-win32-x64/
