name: Build Nativefier App

on:
  push:
    branches:
      - main

jobs:
  build-win:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Nativefier globally
        run: npm install -g nativefier

      - name: Build Windows Nativefier app with icon
        run: |
          nativefier "https://dvd.rpcgroup.xyz" --name "RPClogo DVD" --fullscreen --disable-dev-tools --platform win32 --icon logo.png

      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v4
        with:
          name: RPClogoDVD-win32-x64
          path: RPClogo\ DVD-win32-x64/
