      - name: Build Nativefier app (verbose)
        run: nativefier --name "RPClogoDVD" --icon "./RPClogo.ico" --platform win32 --arch x64 --verbose "https://dvd.rpcgroup.xyz"

      - name: List workspace after build
        run: ls -la

      - name: List all directories matching pattern
        run: ls -ld *-win32-x64 || echo "No directories found matching *-win32-x64"

      - name: Find build output directory
        id: finddir
        run: |
          folder=$(ls -d *-win32-x64 2>/dev/null || echo "")
          echo "Found folder: $folder"
          echo "folder=$folder" >> $GITHUB_OUTPUT

      - name: Upload build artifact
        if: steps.finddir.outputs.folder != ''
        uses: actions/upload-artifact@v4
        with:
          name: RPClogoDVD-win32-x64
          path: ${{ steps.finddir.outputs.folder }}
